#mongodb:
#  primary:
#    host: localhost
#    port: 27017
#    database: teamwork
spring:
  data:
    mongodb:
        host: 192.168.0.103
        port: 27017
        database: teamwork
#        username: root
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8
#    content-type: text/html
#    mode: HTML
#  secondary:
#    host: 192.168.9.60
#    port: 20000
#    database: test1
